### ISSUE TITLE
wscat error: getaddrinfo ENOTFOUND --no-color --no-color:80

### ISSUE THREAD

**Issue by faustf** [websockets/wscat#143] opened 2022-10-18 12:16 UTC
Hi why if in linux mint 54 last release  if i run wscat 5.2.0  wscat --no-color wss://stream.binance.com:9443/ws/bnbusdt@depth20@100ms  return me error error: getaddrinfo ENOTFOUND --no-color --no-color:80
but if i run wscat -c wss://stream.binance.com:9443/ws/bnbusdt@depth20@100ms    work correct ??   thanks

**Comment by lpinca** [comment] 2022-12-17 19:12
This works on my machine:

```
wscat --no-color -c wss://stream.binance.com:9443/ws/bnbusdt@depth20@100ms
```

Make sure to use the correct options. I'm closing this as I can't reproduce the issue. Please comment with more details if needed.

**Closed by lpinca** 2022-12-17 19:12 UTC
