### ISSUE TITLE
possible duplicate with wsd

### ISSUE THREAD

**Issue by derhuerst** [websockets/wscat#19] opened 2016-03-05 13:09 UTC
Just as a reminder, this project is a possible duplicate of [_wsd_](https://github.com/alexanderGugel/wsd), except that it is written in Go.

**Comment by 3rd-Eden** [comment] 2016-03-05 14:09
Or.. WSD is a duplicate of this project. 

Arnout Kazemier

**Closed** 2017-01-25 18:34 UTC
