### ISSUE TITLE
Pipe to another command

### ISSUE THREAD

**Issue by raine** [websockets/wscat#18] opened 2016-03-02 17:23 UTC
Does not seem to be possible currently.

**Comment by mayanklahiri** [comment] 2016-08-08 17:35
Maintainer: would you be willing to accept a PR for this, along with other pipe-related issues? Perhaps a --console flag that removes output decoration and waits for a connection before piping stdin? This would allow wscat to be used in a similar manner to curl/netcat.

**Comment by esphen** [comment] 2016-08-08 17:43
The maintainer has not been active in this space for some time, note the 6 pending PRs. If you need a tool to do this for you, I made a similar tool called [wsta](https://github.com/esphen/wsta/) inspired by wscat some time ago.

**Comment by nwwells** [comment] 2017-01-24 18:53
> maintainer has not been active in this space for some time

Not so. He merged a PR that I worked on recently, and there are only 4 PRs right now. Presumably, if you bother @lpinca, he'll respond.

**Comment by nwwells** [comment] 2017-01-24 18:54
BTW, this is a duplicate of #2, or, at least the fix seems the same in my mind.

**Comment by esphen** [comment] 2017-01-24 19:02
If that has changed, then that is definitely good news for the project. But it was _very_ true when I commented last year.

**Comment by lpinca** [comment] 2017-01-24 19:20
This repo is bit off my radar. @nwwells I've sent you an invite to become a collaborator.

**Comment by nwwells** [comment] 2017-01-24 20:46
Got it. @mayanklahiri, do you think you could submit a PR for this and I'll take a look?

**Comment by nwwells** [comment] 2017-02-21 15:58
Fixed in a2ae4f59773d5848b8a15c6dc7014ca8f8180b8c and 2de4e0f0a7341b83024cde0a3a1e7403a132f001. Will be released with 1.2.0 (see #35)

**Closed by nwwells** 2017-02-21 15:58 UTC
